config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Users', 'action' => 'login']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes. See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
//Plugin::routes();

src/Model/Entity/Account.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Account Entity
 *
 * @property int $id
 * @property string $account_type
 * @property int $customer_id
 * @property string $ref_no
 * @property float $amount
 * @property float $interest
 * @property float $total_weight
 * @property float $net_weight
 * @property float $property_value
 * @property string $status
 * @property \Cake\I18n\FrozenTime $created
 * @property \Cake\I18n\FrozenTime $modified
 *
 * @property \App\Model\Entity\Customer $customer
 * @property \App\Model\Entity\AccountDetail[] $account_details
 */
class Account extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'account_type' => true,
        'customer_id' => true,
        'ref_no' => true,
        'amount' => true,
        'interest' => true,
        'collect_first_month_interest' => true,
        'total_weight' => true,
        'net_weight' => true,
        'property_value' => true,
        'status' => true,
        'created' => true,
        'loan_date' => true,
        'modified' => true,
        'customer' => true,
        'account_details' => true,
        'account_pledge_detail' => true
    ];

    protected function _getDuration()
    {
        $now = time(); // or your date as well
        $loanDate = strtotime($this->loan_date);
        $datediff = $now - $loanDate;

        $days = 0;
        if($datediff > 0)
            $days = round($datediff / (60 * 60 * 24));
        return $days;
    }

    protected function _getIsOldest()
    {
        return ($this->duration >= 180);
    }

    protected function _getAjaxLink()
    {
        return "<a href=\"".
            \Cake\Routing\Router::url(['controller' => 'Accounts', 'action' => 'ajaxview']) ."/".
            $this->id."\" data-reveal-id=\"accountModal\" data-reveal-ajax=\"true\">" . $this->ref_no . "</a>"; 
    }
}

src/Model/Entity/Customer.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;
use Cake\ORM\TableRegistry;

/**
 * Customer Entity
 *
 * @property int $id
 * @property string $firstname
 * @property string $father_or_spouse
 * @property string $lastname
 * @property string $gender
 * @property string $photo
 * @property string $identity_type
 * @property string $identity_code
 * @property string $identity_file
 * @property \Cake\I18n\FrozenTime $created
 * @property \Cake\I18n\FrozenTime $modified
 *
 * @property \App\Model\Entity\Account[] $accounts
 */
class Customer extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'firstname' => true,
        'father_or_spouse' => true,
        'lastname' => true,
        'gender' => true,
        'photo' => true,
        'identity_type' => true,
        'identity_code' => true,
        'identity_file' => true,
        'created' => true,
        'modified' => true,
        'customer_addres' => true,
        'guaranteer_addres' => true,
        'guaranteer' => true,
        'guaranteer_id' => true
    ];

    public function getCustomerHistory()
    {
        $account_model = TableRegistry::get('Accounts');
        $accounts = $account_model->find('all', [
            'conditions' => ['customer_id' => $this->id, 'status' => 'opened']
        ]);
        return $accounts;
    }

    protected function _getMinDetail()
    {
        $full_detail = "";
        $full_detail .= $this->firstname . ", ";
        if($this->gender == 'M') {
            if($this->father_or_spouse == 'F') {
                $full_detail .= "S/O, ";
            } else if($this->father_or_spouse == 'S') {
                $full_detail .= "H/O, ";
            }
        } else if($this->gender == 'F') {
            if($this->father_or_spouse == 'F') {
                $full_detail .= "D/O, ";
            } else if($this->father_or_spouse == 'S') {
                $full_detail .= "W/O, ";
            }
        }
        $full_detail .= $this->lastname;
        return $full_detail;
    }

    protected function _getFullDetail()
    {
        $full_detail = "";
        $full_detail .= $this->firstname . ", ";
        $pre_txt = "";
        if($this->gender == 'M') {
            if($this->father_or_spouse == 'F') {
                $full_detail .= "S/O, ";
                $pre_txt = "திரு. ";
            } else if($this->father_or_spouse == 'S') {
                $full_detail .= "H/O, ";
                $pre_txt = "திரு. ";
            }
        } else if($this->gender == 'F') {
            if($this->father_or_spouse == 'F') {
                $full_detail .= "D/O, ";
                $pre_txt = "செல்வி. ";
            } else if($this->father_or_spouse == 'S') {
                $full_detail .= "W/O, ";
                $pre_txt = "திருமதி. ";
            }
        }
        $full_detail .= $this->lastname;
        if($this->customer_addres) {
            $full_detail .= "<br/>";
            $full_detail .= $this->customer_addres->door_no . ", ";
            $full_detail .= $this->customer_addres->street . "<br/>";
            $full_detail .= $this->customer_addres->area . ", ";
            $full_detail .= $this->customer_addres->village . "<br/>";
            $full_detail .= $this->customer_addres->city . ", ";
            $full_detail .= $this->customer_addres->pincode . "<br/>";
            $full_detail .= $this->customer_addres->mobile . ", ";
            $full_detail .= $this->customer_addres->phone;
        }
        return $pre_txt . $full_detail;
    }
}

src/Model/Table/AccountsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;
use Cake\Routing\Router;
use Cake\ORM\TableRegistry;

/**
 * Accounts Model
 *
 * @property \App\Model\Table\CustomersTable|\Cake\ORM\Association\BelongsTo $Customers
 * @property \App\Model\Table\AccountDetailsTable|\Cake\ORM\Association\HasMany $AccountDetails
 *
 * @method \App\Model\Entity\Account get($primaryKey, $options = [])
 * @method \App\Model\Entity\Account newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Account[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Account|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Account|bool saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Account patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Account[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Account findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class AccountsTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('accounts');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Customers', [
            'foreignKey' => 'customer_id'
        ]);

        $this->hasMany('AccountDetails', [
            'foreignKey' => 'account_id',
            'dependent' => true,
            'cascadeCallbacks' => true
        ]);

        $this->hasOne('AccountPledgeDetail', [
            'foreignKey' => 'account_id',
            'dependent' => true,
            'cascadeCallbacks' => true
        ]);

        $this->hasMany('Receipts', [
            'foreignKey' => 'account_id',
            'dependent' => true,
            'cascadeCallbacks' => true
        ]);

        $this->belongsTo('CreatedUser', [
                'className' => 'Users'
            ])
            ->setForeignKey('created_by')
            ->setProperty('created_user');

        $this->belongsTo('ModifiedUser', [
                'className' => 'Users'
            ])
            ->setForeignKey('modified_by')
            ->setProperty('modified_user');
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->scalar('account_type')
            ->notEmpty('account_type');

        $validator
            ->scalar('ref_no')
            ->maxLength('ref_no', 50)
            ->notEmpty('ref_no');

        $validator->add(
            'ref_no', 
            ['unique' => [
                'rule' => 'validateUnique', 
                'provider' => 'table', 
                'message' => 'Already exists']
            ]
        );

        $validator
            ->date('loan_date')
            ->requirePresence('loan_date', 'create')
            ->notEmpty('loan_date');

        $validator
            ->decimal('amount')
            ->notEmpty('amount');

        $validator
            ->decimal('interest')
            ->notEmpty('interest');

        $validator
            ->decimal('total_weight')
            ->notEmpty('total_weight');

        if(env('NET_WEIGHT_REQUIRED') == "true") {
            $validator
                ->decimal('net_weight')
                ->notEmpty('net_weight');
        } else {
            $validator
                ->decimal('net_weight')
                ->allowEmpty('net_weight');
        }

        $validator
            ->decimal('property_value')
            ->notEmpty('property_value');

        $validator
            ->scalar('status')
            ->maxLength('status', 50)
            ->allowEmpty('status');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['customer_id'], 'Customers'));

        return $rules;
    }

    public function beforeFind($query) {
        $loggedUser = Router::getRequest()->getSession()->read('Auth.User');
        if($loggedUser) {
            if($loggedUser['role'] != 'admin') {
                //$query['conditions']['account_type'] = 'direct';
            }
        }
        return $query;
    }

    public function beforeSave($event, $entity, $options) {
        $userId = isset($_SESSION['Auth']['User']['id']) ? $_SESSION['Auth']['User']['id'] : 0;
        if($entity->isNew()) {
            $entity->created_by = $userId;
        } else {
            $entity->modified_by = $userId;
        }
    }

    public function afterSave($event, $entity, $options) {
        if($entity->isNew()) {
            $receipt_model = TableRegistry::get('Receipts');
            $receipt = $receipt_model->newEntity();
            $receipt->account_id = $entity->id;
            $receipt->pdate = $entity->loan_date;
            $receipt->payment_type = 'loan';
            $receipt->principal = $entity->amount;
            $receipt->interest = 0;
            $receipt->amount = $entity->amount;
            $receipt->created = $entity->loan_date;
            $receipt->modified = $entity->loan_date;
            $receipt_model->save($receipt);
            
            if($entity->collect_first_month_interest == 1) {
                $duration = 30;
                $interest = $entity->amount * ($entity->interest / 100)  * ($duration / 30);
                $receipt = $receipt_model->newEntity();
                $receipt->account_id = $entity->id;
                $receipt->pdate = $entity->loan_date;
                $receipt->duration = $duration;
                $receipt->payment_type = 'interest';
                $receipt->interest = $interest;
                $receipt->principle = 0;
                $receipt->amount = $interest;
                $receipt->created = $entity->loan_date;
                $receipt->modified = $entity->loan_date;
                $receipt_model->save($receipt);
            }
        }
    }
}

src/Template/Accounts/export.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Account[]|\Cake\Collection\CollectionInterface $accounts
 */
$cakeDescription = 'Finus Web';
?>
<!DOCTYPE html>
<html>
<head>
    <?= $this->Html->charset() ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        <?= $cakeDescription ?>:
        <?= $this->fetch('title') ?>
    </title>
    <?= $this->Html->meta('icon') ?>

    <?= $this->Html->css('base.css') ?>
    
    <style type="text/css">
        table, th, td {
            border: 1px solid black;
        }

        page {
          background: white;
          display: block;
          margin: 0 auto;
          margin-bottom: 0.5cm;
          /*box-shadow: 0 0 0.5cm rgba(0,0,0,0.5);*/
        }
        page[size="A4"] {  
          width: 21cm;
          height: 29.7cm; 
        }
        page[size="A4"][layout="portrait"] {
          width: 29.7cm;
          height: 21cm;  
        }
        page[size="A3"] {
          width: 29.7cm;
          height: 42cm;
        }
        page[size="A3"][layout="portrait"] {
          width: 42cm;
          height: 29.7cm;  
        }
        page[size="A5"] {
          width: 14.8cm;
          height: 21cm;
        }
        page[size="A5"][layout="portrait"] {
          width: 21cm;
          height: 14.8cm;  
        }
        @media print {
          body, page {
            margin: 0;
            box-shadow: 0;
          }
        }
    </style>
</head>
<body>
    <page size="A4">
        <div class="accounts index large-12 medium-12 columns content">
            <h3><?= __('Report - Accounts') ?></h3>
           
            <table cellpadding="0" cellspacing="0">
                <thead>
                    <tr>
                        <th width="150">Acc Ref No</th>
                        <th width="80">Cust-ID</th>
                        <th width="280">Customer</th>
                        <th width="150" style="text-align: right">Loan Amount (Rs)</th>
                        <th width="180">Loan Date</th>
                        <th width="100">Status</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($accounts as $account): ?>
                    <tr style="<?=$account->is_oldest ? 'background: #FBD0D5;' : ''?>">
                        <td>
                            <?php if($account->is_oldest) : ?>
                                <b style="color: red"><?= $account->ref_no;?></b> (<?=$account->duration?> days)
                            <?php else : ?>
                                <?= $account->ref_no;?>
                            <?php endif; ?>
                        </td>
                        <?php if(!$account->customer) : ?>
                            <td>-</td>
                            <td>-</td>
                        <?php else : ?>
                            <td><?=h($account->customer->id)?></td>
                            <td>
                                <?= ($account->customer->full_detail)?>
                            </td>
                        <?php endif;?>
                        <td style="text-align: right"><b><?= h($account->amount)?></b></td>
                        <td><?= $this->Time->format($account->loan_date, 'dd-MMM-yyyy hh:mm a') ?></td>
                        <td>
                            <?php if($account->status == 'opened') : ?>
                                <span class="label">Active</span>
                            <?php else : ?>
                                <span class="label alert">Closed</span>
                            <?php endif;?>
                        </td>
                    </tr>
                    <?php endforeach;?>
                </tbody>
            </table>
        </div>
    </page>
</body>
</html>

src/Template/Accounts/index.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Account[]|\Cake\Collection\CollectionInterface $accounts
 */
?>

<div class="accounts index large-12 medium-12 columns content">
    <h3><?= __('Accounts') ?></h3>
    <div class="filters">
        <?php echo $this->Form->create("Filter",array('class' => 'filter', 'type' => 'GET'));?>
        <div class="row">
            <div class="large-4 columns">
                <?php echo $this->Form->input("search", array('label' => 'Search', 'placeholder' => "Search...", 'value' => isset($_GET['search']) ? $_GET['search'] : ''));?>
            </div>

            <div class="large-4 columns">
                <?php echo $this->Form->input("search_by", ['label' => 'By', 'options' => [
                    '' => 'Any',
                    'ref_no' => 'Reference No',
                    'Customers.id' => 'Customer ID',
                    'firstname' => 'First name',
                    'lastname' => 'Last name',
                    'identity_code' => 'Identity Code',
                    'CustomerAddress.mobile' => 'Mobile',
                    'CustomerAddress.phone' => 'Phone',
                    'CustomerAddress.door_no' => 'Door No',
                    'CustomerAddress.street' => 'Street',
                    'CustomerAddress.area' => 'Area',
                    'CustomerAddress.village' => 'Village',
                    'CustomerAddress.City' => 'City',
                    'CustomerAddress.pincode' => 'Pin Code'
                ], 'value' => isset($_GET['search_by']) ? $_GET['search_by'] : '']);?>
            </div>
            <div class="large-2 columns">
                <?php echo $this->Form->input("status", ['label' => 'Status', 'options' => [
                    '' => 'All',
                    'opened' => 'Active',
                    'closed' => 'Closed'
                ], 'value' => isset($_GET['status']) ? $_GET['status'] : '']);?>
            </div>
            <div class="large-2 columns">
                <?php echo $this->Form->submit("Search", ['style' => 'margin-top: 18px', 'class'=>'button small info']);?>
            </div>
        </div>
        <?php echo $this->Form->end();?>
    </div>
    <table cellpadding="0" cellspacing="0">
        <thead>
            <tr>
                <th width="130"><?php echo $this->Paginator->sort('CAST(Accounts.ref_no AS UNSIGNED)', 'Ref No');?></th>
                <th width="80"><?php echo $this->Paginator->sort('Customers.id', 'Cust-ID');?></th>
                <th width="260"><?php echo $this->Paginator->sort('Customers.firstname', 'Customer');?></th>
                <th width="150">History</th>
                <th width="120"><?php echo $this->Paginator->sort('Accounts.amount', 'Amount (Rs)');?></th>
                <th width="110"><?php echo $this->Paginator->sort('Accounts.loan_date', 'Loan Date');?></th>
                <th width="100"><?php echo $this->Paginator->sort('Accounts.status', 'Status');?></th>
                <th width="280">Actions</th>
                <th width="130"><?php echo $this->Paginator->sort('CreatedUser.username', 'Created');?></th>
                <th width="130"><?php echo $this->Paginator->sort('ModifiedUser.username', 'Modified');?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($accounts as $account): ?>
            <tr style="<?=$account->is_oldest ? 'background: #FBD0D5;' : ''?>">
                <td>
                    <a href="accounts/ajaxview/<?=$account->id?>" data-reveal-id="accountModal" data-reveal-ajax="true">
                        <?php if($account->is_oldest) : ?>
                            <b style="color: red"><?= $account->ref_no;?></b> (<?=$account->duration?> days)
                        <?php else : ?>
                            <?= $account->ref_no;?>
                        <?php endif; ?>
                    </a>
                </td>
                <?php if(!$account->customer) : ?>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                <?php else : ?>
                    <td><?=h($account->customer->id)?></td>
                    <td>
                        <?= $this->Html->link(($account->customer->min_detail), ['controller' => 'Customers', 'action' => 'loadview', $account->customer->id], ['escape'=>false, 'class'=>'', 'data-reveal-id' => 'customerModal', 'data-reveal-ajax' => 'true']) ?>
                    </td>
                    <td>
                        <?php 
                            $histories = $account->customer->getCustomerHistory();
                            $totalHis = 0;
                            $oldestHis = 0;
                            foreach ($histories as $key => $history) {
                                if($history->is_oldest) {
                                    $oldestHis++;
                                }
                                $totalHis++;
                            }
                        ?>
                        <?php if($oldestHis > 0) : ?>
                            <span class="label alert"><?=$oldestHis?> of <?=$totalHis?> Account(s)</span>
                        <?php else : ?>
                            <span class="label info"><?=$totalHis?> Account(s)</span>
                        <?php endif;?>
                    </td>
                <?php endif;?>
                <td><b><?= $this->Number->format($account->amount)?></b></td>
                <td><?= $this->Time->format($account->loan_date, 'dd-MMM-yyyy') ?></td>
                <td>
                    <?php if($account->status == 'opened') : ?>
                        <span class="label">Active</span>
                    <?php else : ?>
                        <span class="label alert">Closed</span>
                    <?php endif;?>
                </td>
                <td class="actions" style="text-align: center;">
                    <?= $this->Html->link(('<i class="fa fa-print"></i>' . ""), ['controller' => 'Accounts', 'action' => 'print', $account->id], ['escape'=>false, 'class'=>'label info', 'target' => '_new']) ?>
                    <?= $this->Html->link(('<i class="fa fa-book"></i>' . " Receipts"), ['controller' => 'Receipts', 'action' => 'add', 'account_id' => $account->id], ['escape'=>false, 'class'=>'label info']) ?>
                    <?= $this->Html->link(('<i class="fa fa-eye"></i>' . " View"), ['action' => 'view', $account->id], ['escape'=>false, 'class'=>'label']) ?>
                    <?php if($user_role == 'admin') : ?>
                    <?= $this->Html->link('<i class="fa fa-pencil"></i>' . ' Edit', ['action' => 'edit', $account->id], ['escape'=>false, 'class'=>'label success']) ?>
                    <?= $this->Form->postLink('<i class="fa fa-trash-o"></i>' . ' Delete', ['action' => 'delete', $account->id], ['escape'=>false, 'class'=>'label alert', 'confirm' => __('Are you sure you want to delete # {0}?', $account->id)]) ?>
                    <?php endif?>
                </td>

                <td>
                    <?=$account->created_user ? $account->created_user->username : '';?>
                </td>
                <td>
                    <?=$account->modified_user ? $account->modified_user->username : '';?>
                </td>
            </tr>
            <?php endforeach;?>
        </tbody>
    </table>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->first('<< ' . __('first')) ?>
            <?= $this->Paginator->prev('< ' . __('previous')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('next') . ' >') ?>
            <?= $this->Paginator->last(__('last') . ' >>') ?>
        </ul>
        <p><?= $this->Paginator->counter(['format' => __('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')]) ?></p>
    </div>
</div>

<div id="customerModal" class="reveal-modal xlarge" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog" style="max-height: 500px; overflow-y: scroll;">
    <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

<div id="accountModal" class="reveal-modal xlarge" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog" style="max-height: 500px; overflow-y: scroll;">
    <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>